name: Feature-Deploy.
on: 
   push: 
    branches: 
        - 'feature**'
jobs: 
    testing: 
      name: Verify code. 
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Configure node
          uses: actions/setup-node@v2
          with:
            node-version: '18'
  
        - name: Install dependencies
          run: npm install
  
        - name: Run tests
          run: npm test
        